install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- bash ./config/create-env.sh
script:
- cd tests
- bash run.sh
- cd ..
deploy:
  provider: pypi
  user: __token__
  password:
    secure: cM5yCUahOCAEXiI30aiL9H94rTUEwq+MIRL4UguZNo8dLG+c3Ho7dUqUbGzyhequbx+yQMWFSR+TGvsnB8Gv3xaaEciPhctMZws2ASpLdNco+b9p4g9/wgBDBlnycTbsywmCudxu7vASpOk3FPIGuNgY5FhEXGRjGAuLjRkQhyie9wGTpN+xWEQpfWiZhvFxj8DaMYiya5DwG5VYM2EoU9CqqtQLI9JWdiU/iu2r9EPe4mAH2lw1fIaeKpcxvf4e4hf8cnzJSHX88S5SiLJY5GUDSwIKBHX3nun1Y4DMP3hfQigNM8vVD0Pr1Wvg/jNplnZPya8rleBodIQ9hJyf9sRFJZbp2KeSlZdgluN79bN06dPjJ5iay3dZt/zUhi6vMvprjaJszGUFk2dWwMJt0TR5lAclQSU8dfwjMU0DZe+K90/rzo5LXZW7QZU4r5Fc7bjAtvwh6gys+UyfsymNIMP55FKyXLpghGK5rTeDrwqT+0dnzfjpT7VODEg7U3EV9hSHng6NTzPO2RpanpV5bOyp2tNcD63wdlSnP8zFJtLZfxpp9949H5ko51BgYwBFQ539mdb8Ly/gZMxesKMZ82MuGJKYz5/VyPwewkNIqtELGzOOuZsZRrBYYbnOHntbOIKb/OsjnFm6d5e5Z+v4xQ/YiVqx8SDOP6GweWOSgr0=
