#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: ./nb/template.ipynb
import sys
if __name__ == '__main__': sys.path.append('..')
import x_lib.common as common